package com.xinniu.android.qiqueqiao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xinniu.android.qiqueqiao.bean.GroupBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP_BEAN".
*/
public class GroupBeanDao extends AbstractDao<GroupBean, Long> {

    public static final String TABLENAME = "GROUP_BEAN";

    /**
     * Properties of entity GroupBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Theid = new Property(0, Long.class, "theid", true, "_id");
        public final static Property Id = new Property(1, int.class, "id", false, "ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Head_pic = new Property(3, String.class, "head_pic", false, "HEAD_PIC");
        public final static Property Status = new Property(4, int.class, "status", false, "STATUS");
        public final static Property Create_time = new Property(5, int.class, "create_time", false, "CREATE_TIME");
        public final static Property Category = new Property(6, int.class, "category", false, "CATEGORY");
        public final static Property Level = new Property(7, int.class, "level", false, "LEVEL");
        public final static Property Is_top = new Property(8, int.class, "is_top", false, "IS_TOP");
        public final static Property Sort_order = new Property(9, int.class, "sort_order", false, "SORT_ORDER");
        public final static Property User_id = new Property(10, int.class, "user_id", false, "USER_ID");
        public final static Property Notice = new Property(11, String.class, "notice", false, "NOTICE");
        public final static Property Type = new Property(12, int.class, "type", false, "TYPE");
        public final static Property Introduction = new Property(13, String.class, "introduction", false, "INTRODUCTION");
        public final static Property Is_verify = new Property(14, int.class, "is_verify", false, "IS_VERIFY");
        public final static Property Is_send = new Property(15, int.class, "is_send", false, "IS_SEND");
        public final static Property Is_v = new Property(16, int.class, "is_v", false, "IS_V");
        public final static Property Is_vip = new Property(17, int.class, "is_vip", false, "IS_VIP");
        public final static Property Num = new Property(18, int.class, "num", false, "NUM");
        public final static Property Share_url = new Property(19, String.class, "share_url", false, "SHARE_URL");
        public final static Property UnReadMesCount = new Property(20, int.class, "unReadMesCount", false, "UN_READ_MES_COUNT");
    }


    public GroupBeanDao(DaoConfig config) {
        super(config);
    }
    
    public GroupBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: theid
                "\"ID\" INTEGER NOT NULL ," + // 1: id
                "\"NAME\" TEXT," + // 2: name
                "\"HEAD_PIC\" TEXT," + // 3: head_pic
                "\"STATUS\" INTEGER NOT NULL ," + // 4: status
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 5: create_time
                "\"CATEGORY\" INTEGER NOT NULL ," + // 6: category
                "\"LEVEL\" INTEGER NOT NULL ," + // 7: level
                "\"IS_TOP\" INTEGER NOT NULL ," + // 8: is_top
                "\"SORT_ORDER\" INTEGER NOT NULL ," + // 9: sort_order
                "\"USER_ID\" INTEGER NOT NULL ," + // 10: user_id
                "\"NOTICE\" TEXT," + // 11: notice
                "\"TYPE\" INTEGER NOT NULL ," + // 12: type
                "\"INTRODUCTION\" TEXT," + // 13: introduction
                "\"IS_VERIFY\" INTEGER NOT NULL ," + // 14: is_verify
                "\"IS_SEND\" INTEGER NOT NULL ," + // 15: is_send
                "\"IS_V\" INTEGER NOT NULL ," + // 16: is_v
                "\"IS_VIP\" INTEGER NOT NULL ," + // 17: is_vip
                "\"NUM\" INTEGER NOT NULL ," + // 18: num
                "\"SHARE_URL\" TEXT," + // 19: share_url
                "\"UN_READ_MES_COUNT\" INTEGER NOT NULL );"); // 20: unReadMesCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroupBean entity) {
        stmt.clearBindings();
 
        Long theid = entity.getTheid();
        if (theid != null) {
            stmt.bindLong(1, theid);
        }
        stmt.bindLong(2, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String head_pic = entity.getHead_pic();
        if (head_pic != null) {
            stmt.bindString(4, head_pic);
        }
        stmt.bindLong(5, entity.getStatus());
        stmt.bindLong(6, entity.getCreate_time());
        stmt.bindLong(7, entity.getCategory());
        stmt.bindLong(8, entity.getLevel());
        stmt.bindLong(9, entity.getIs_top());
        stmt.bindLong(10, entity.getSort_order());
        stmt.bindLong(11, entity.getUser_id());
 
        String notice = entity.getNotice();
        if (notice != null) {
            stmt.bindString(12, notice);
        }
        stmt.bindLong(13, entity.getType());
 
        String introduction = entity.getIntroduction();
        if (introduction != null) {
            stmt.bindString(14, introduction);
        }
        stmt.bindLong(15, entity.getIs_verify());
        stmt.bindLong(16, entity.getIs_send());
        stmt.bindLong(17, entity.getIs_v());
        stmt.bindLong(18, entity.getIs_vip());
        stmt.bindLong(19, entity.getNum());
 
        String share_url = entity.getShare_url();
        if (share_url != null) {
            stmt.bindString(20, share_url);
        }
        stmt.bindLong(21, entity.getUnReadMesCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroupBean entity) {
        stmt.clearBindings();
 
        Long theid = entity.getTheid();
        if (theid != null) {
            stmt.bindLong(1, theid);
        }
        stmt.bindLong(2, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String head_pic = entity.getHead_pic();
        if (head_pic != null) {
            stmt.bindString(4, head_pic);
        }
        stmt.bindLong(5, entity.getStatus());
        stmt.bindLong(6, entity.getCreate_time());
        stmt.bindLong(7, entity.getCategory());
        stmt.bindLong(8, entity.getLevel());
        stmt.bindLong(9, entity.getIs_top());
        stmt.bindLong(10, entity.getSort_order());
        stmt.bindLong(11, entity.getUser_id());
 
        String notice = entity.getNotice();
        if (notice != null) {
            stmt.bindString(12, notice);
        }
        stmt.bindLong(13, entity.getType());
 
        String introduction = entity.getIntroduction();
        if (introduction != null) {
            stmt.bindString(14, introduction);
        }
        stmt.bindLong(15, entity.getIs_verify());
        stmt.bindLong(16, entity.getIs_send());
        stmt.bindLong(17, entity.getIs_v());
        stmt.bindLong(18, entity.getIs_vip());
        stmt.bindLong(19, entity.getNum());
 
        String share_url = entity.getShare_url();
        if (share_url != null) {
            stmt.bindString(20, share_url);
        }
        stmt.bindLong(21, entity.getUnReadMesCount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GroupBean readEntity(Cursor cursor, int offset) {
        GroupBean entity = new GroupBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // theid
            cursor.getInt(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // head_pic
            cursor.getInt(offset + 4), // status
            cursor.getInt(offset + 5), // create_time
            cursor.getInt(offset + 6), // category
            cursor.getInt(offset + 7), // level
            cursor.getInt(offset + 8), // is_top
            cursor.getInt(offset + 9), // sort_order
            cursor.getInt(offset + 10), // user_id
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // notice
            cursor.getInt(offset + 12), // type
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // introduction
            cursor.getInt(offset + 14), // is_verify
            cursor.getInt(offset + 15), // is_send
            cursor.getInt(offset + 16), // is_v
            cursor.getInt(offset + 17), // is_vip
            cursor.getInt(offset + 18), // num
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // share_url
            cursor.getInt(offset + 20) // unReadMesCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroupBean entity, int offset) {
        entity.setTheid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHead_pic(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStatus(cursor.getInt(offset + 4));
        entity.setCreate_time(cursor.getInt(offset + 5));
        entity.setCategory(cursor.getInt(offset + 6));
        entity.setLevel(cursor.getInt(offset + 7));
        entity.setIs_top(cursor.getInt(offset + 8));
        entity.setSort_order(cursor.getInt(offset + 9));
        entity.setUser_id(cursor.getInt(offset + 10));
        entity.setNotice(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setType(cursor.getInt(offset + 12));
        entity.setIntroduction(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setIs_verify(cursor.getInt(offset + 14));
        entity.setIs_send(cursor.getInt(offset + 15));
        entity.setIs_v(cursor.getInt(offset + 16));
        entity.setIs_vip(cursor.getInt(offset + 17));
        entity.setNum(cursor.getInt(offset + 18));
        entity.setShare_url(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setUnReadMesCount(cursor.getInt(offset + 20));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GroupBean entity, long rowId) {
        entity.setTheid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GroupBean entity) {
        if(entity != null) {
            return entity.getTheid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroupBean entity) {
        return entity.getTheid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
