package com.xinniu.android.qiqueqiao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xinniu.android.qiqueqiao.bean.OtherUserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OTHER_USER_INFO".
*/
public class OtherUserInfoDao extends AbstractDao<OtherUserInfo, Long> {

    public static final String TABLENAME = "OTHER_USER_INFO";

    /**
     * Properties of entity OtherUserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, int.class, "user_id", false, "USER_ID");
        public final static Property Realname = new Property(2, String.class, "realname", false, "REALNAME");
        public final static Property Head_pic = new Property(3, String.class, "head_pic", false, "HEAD_PIC");
        public final static Property Company = new Property(4, String.class, "company", false, "COMPANY");
        public final static Property Position = new Property(5, String.class, "position", false, "POSITION");
        public final static Property Company_name = new Property(6, String.class, "company_name", false, "COMPANY_NAME");
        public final static Property Follow_status = new Property(7, int.class, "follow_status", false, "FOLLOW_STATUS");
        public final static Property Is_vip = new Property(8, String.class, "is_vip", false, "IS_VIP");
        public final static Property Is_corporate_vip = new Property(9, String.class, "is_corporate_vip", false, "IS_CORPORATE_VIP");
    }


    public OtherUserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public OtherUserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OTHER_USER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: user_id
                "\"REALNAME\" TEXT," + // 2: realname
                "\"HEAD_PIC\" TEXT," + // 3: head_pic
                "\"COMPANY\" TEXT," + // 4: company
                "\"POSITION\" TEXT," + // 5: position
                "\"COMPANY_NAME\" TEXT," + // 6: company_name
                "\"FOLLOW_STATUS\" INTEGER NOT NULL ," + // 7: follow_status
                "\"IS_VIP\" TEXT," + // 8: is_vip
                "\"IS_CORPORATE_VIP\" TEXT);"); // 9: is_corporate_vip
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OTHER_USER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OtherUserInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
 
        String realname = entity.getRealname();
        if (realname != null) {
            stmt.bindString(3, realname);
        }
 
        String head_pic = entity.getHead_pic();
        if (head_pic != null) {
            stmt.bindString(4, head_pic);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(5, company);
        }
 
        String position = entity.getPosition();
        if (position != null) {
            stmt.bindString(6, position);
        }
 
        String company_name = entity.getCompany_name();
        if (company_name != null) {
            stmt.bindString(7, company_name);
        }
        stmt.bindLong(8, entity.getFollow_status());
 
        String is_vip = entity.getIs_vip();
        if (is_vip != null) {
            stmt.bindString(9, is_vip);
        }
 
        String is_corporate_vip = entity.getIs_corporate_vip();
        if (is_corporate_vip != null) {
            stmt.bindString(10, is_corporate_vip);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OtherUserInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
 
        String realname = entity.getRealname();
        if (realname != null) {
            stmt.bindString(3, realname);
        }
 
        String head_pic = entity.getHead_pic();
        if (head_pic != null) {
            stmt.bindString(4, head_pic);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(5, company);
        }
 
        String position = entity.getPosition();
        if (position != null) {
            stmt.bindString(6, position);
        }
 
        String company_name = entity.getCompany_name();
        if (company_name != null) {
            stmt.bindString(7, company_name);
        }
        stmt.bindLong(8, entity.getFollow_status());
 
        String is_vip = entity.getIs_vip();
        if (is_vip != null) {
            stmt.bindString(9, is_vip);
        }
 
        String is_corporate_vip = entity.getIs_corporate_vip();
        if (is_corporate_vip != null) {
            stmt.bindString(10, is_corporate_vip);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OtherUserInfo readEntity(Cursor cursor, int offset) {
        OtherUserInfo entity = new OtherUserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // realname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // head_pic
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // company
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // position
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // company_name
            cursor.getInt(offset + 7), // follow_status
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // is_vip
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // is_corporate_vip
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OtherUserInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.getInt(offset + 1));
        entity.setRealname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHead_pic(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCompany(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPosition(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCompany_name(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFollow_status(cursor.getInt(offset + 7));
        entity.setIs_vip(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIs_corporate_vip(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OtherUserInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OtherUserInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OtherUserInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
